### PR TITLE
Center Floating button

### PR DESCRIPTION
**Pull request by Ardjlon**
* Center floating button on screen when first opening in portrait and landspace (separate values)
* This prevents the floating button from moving out of range of the screen

### CODE REVIEW

**Review by RealAkito — APPROVED** [review]
Looking good to me

**Comment by jjpprrrr** [comment]
If you decide to hard code a center position, can't we also get rid of the variable `defaultX`?

On the other hand, if we'd like to __fix__ the intended logic instead of changing it, can we calculate `defaultX` conditionally inside the `ScreenUtil.isPortrait()` block, and perhaps use `ScreenUtil. getScreenHeight()` for one of the case? I haven't tested it myself, so I'm just guessing.

**Comment by Ardjlon** [comment]
> If you decide to hard code a center position, can't we also get rid of the variable `defaultX`?
> 
> On the other hand, if we'd like to **fix** the intended logic instead of changing it, can we calculate `defaultX` conditionally inside the `ScreenUtil.isPortrait()` block, and perhaps use `ScreenUtil. getScreenHeight()` for one of the case? I haven't tested it myself, so I'm just guessing.

I don't know much about it, but if you open a game in landspace and move the floating button it will not appear in the same position the next time or it will be literally off the screen, and you will not be able to see the floating button until you delete the data from the app GameCore from the system. Setting the values I made in the change when starting a game for the first time, the button will appear in the center only once in both modes, and when moving it it will save the preferences correctly and when it opens again it will load the values that each mode has saved

**Comment by Ardjlon** [comment]
For example, I ran clash royale and moved the button to the desired position (upper left), then I ran PUBG and the button disappeared completely, this change as you can see in my repository takes a few days, since I had already done tests, and then If I open clash royale the button will come out centered and I move it, it will save that position, and when I open pubg it will come out centered again and when moving it it will save the values in the same way. I see it as a perhaps not permanent solution but it can help as long as someone else with better knowledge can do something different.
Example: https://ibb.co/HDpLjz1

**Comment by jjpprrrr** [comment]
> For example, I ran clash royale and moved the button to the desired position (upper left), then I ran PUBG and the button disappeared completely, this change as you can see in my repository takes a few days, since I had already done tests, and then If I open clash royale the button will come out centered and I move it, it will save that position, and when I open pubg it will come out centered again and when moving it it will save the values in the same way. I see it as a perhaps not permanent solution but it can help as long as someone else with better knowledge can do something different.
> Example: https://ibb.co/HDpLjz1

Yes I understand what you are saying. It is indeed a hack, but if it solves the problem and only affects the initial launch, I'll give it a pass.

Thanks for submitting the patch. I wish I have time to look into this issue, but unfortunately I don't.

**Review by jjpprrrr — APPROVED** [review]

**Comment by jjpprrrr** [comment]
Well the unused variable `defaultX` is still there, but whatever...

**Pull request merged**
